TITLE "V506 HOMEWORK07 - JIVITESH POOJARY AND QIWEN ZHU";

DATA V506.WCtemp;
	SET v506.WILDCATS;
RUN;

PROC REG;
	MODEL WILDCATS = PRICE OUTPUT GNP TIME/STB VIF;
RUN;

PROC REG;
	MODEL WILDCATS = PRICE OUTPUT GNP/STB VIF;
RUN;

PROC CORR;
	VAR WILDCATS PRICE OUTPUT GNP TIME;
RUN;
