TITLE "V506 HOMEWORK07 - JIVITESH POOJARY AND QIWEN ZHU";

DATA V506.REtemp;
	SET v506.REALEST;
RUN;

PROC REG;
	MODEL PRICE = BEDROOMS SIZE DISTANCE BATHS GARAGE POOL;
RUN;

PROC REG;
	MODEL PRICE = BEDROOMS SIZE BATHS GARAGE POOL;
RUN;

PROC CORR;
	VAR PRICE BEDROOMS SIZE DISTANCE BATHS GARAGE POOL;
RUN;
