TITLE "V506 HOMEWORK05 PART 2 - JIVITESH POOJARY AND QIWEN ZHU";

DATA V506.Itemp;
	SET V506.International;
RUN;

PROC ANOVA plots=none data=V506.Itemp;
	CLASS PETROLEUM;
	MODEL PCUNEMP = PETROLEUM;
	MEANS PETROLEUM / BON;
RUN;

PROC ANOVA plots=none;
	CLASS PETROLEUM;
	MODEL LIFEEXPC = PETROLEUM;
	MEANS PETROLEUM / BON;
RUN;
