TITLE "V506 HOMEWORK05 PART 2 - JIVITESH POOJARY AND QIWEN ZHU";

DATA V506.Atemp;
	SET V506.Appalachian;
RUN;

PROC UNIVARIATE;
	VAR EDUCPRC;
RUN;

PROC UNIVARIATE;
	VAR WELFPRC;
RUN;

PROC UNIVARIATE;
	VAR HOUSQUAL;
RUN;


PROC ANOVA plots=none;
	CLASS STATE EDUCLVL;
	MODEL EDUCPRC = STATE EDUCLVL STATE*EDUCLVL;
	MEANS STATE EDUCLVL / BON;
RUN;

PROC ANOVA plots=none;
	CLASS STATE EDUCLVL;
	MODEL WELFPRC = STATE EDUCLVL STATE*EDUCLVL;
	MEANS STATE EDUCLVL / BON;
RUN;

PROC ANOVA plots=none;
	CLASS STATE EDUCLVL;
	MODEL HOUSQUAL = STATE EDUCLVL STATE*EDUCLVL;
	MEANS STATE EDUCLVL / BON;
RUN;
