TITLE "V506 HOMEWORK05 PART 2 - JIVITESH POOJARY AND QIWEN ZHU";

DATA V506.temp;
	SET V506.EZD;
RUN;

PROC UNIVARIATE;
	VAR NEWHIRED;
RUN;

PROC ANOVA plots=none;
	CLASS STATE;
	MODEL NEWHIRED = STATE;
	MEANS STATE / BON;
RUN;
