TITLE "V506 HOMEWORK05 PART 2 - JIVITESH POOJARY AND QIWEN ZHU";

DATA V506.Btemp;
	SET V506.Buses;
RUN;

PROC ANOVA plots=none;
	CLASS BUS_MFG;
	MODEL MAINTENANCE = BUS_MFG;
	MEANS BUS_MFG / BON ALPHA=0.01;
RUN;

PROC ANOVA plots=none;
	CLASS BUS_MFG;
	MODEL MILES  = BUS_MFG;
	MEANS BUS_MFG / BON;
RUN;

DATA V506.Btemp2;
	SET V506.Btemp;
	IF BUS_MFG='Bluebird';
RUN;

PROC MEANS;
	VAR MAINTENANCE;
RUN;

DATA V506.Btemp2;
	SET V506.Btemp;
	IF BUS_MFG='Thompson';
RUN;

PROC MEANS;
	VAR MAINTENANCE;
RUN;
