TITLE "V506 HOMEWORK05 PART 2 - JIVITESH POOJARY AND QIWEN ZHU";

DATA V506.Stemp;
	SET V506.Schools;
RUN;

DATA v506.Stemp2;
	SET v506.Stemp;
	IF STUDENTS<1000 THEN SIZE='small';
	ELSE IF STUDENTS<3000 THEN SIZE='medium';
	ELSE SIZE='large';
RUN;

PROC UNIVARIATE;
	VAR SIZE;
RUN;

PROC ANOVA plots=none;
	CLASS SIZE;
	MODEL INSTRUCT = SIZE;
	MEANS SIZE / BON;
RUN;

PROC ANOVA plots=none;
	CLASS SIZE;
	MODEL SALARY = SIZE;
	MEANS SIZE / BON;
RUN;
