TITLE "V506 HOMEWORK04 PART 2 - JIVITESH POOJARY AND QIWEN ZHU";

DATA temp;
	SET V506.RealEstate;
RUN;

PROC PRINT;
RUN;

PROC FREQ DATA=temp;
	  TABLES pool / BINOMIAL(LEVEL=2) ALPHA=.05;
	  TABLES pool / BINOMIAL(LEVEL=1) ALPHA=.05;
RUN;

PROC TTEST DATA=v506.RealEstate PLOTS=none;
CLASS Pool;
VAR Price;
RUN;

PROC MEANS;
	CLASS Pool;
	VAR Price;
RUN;
