TITLE "V506 HOMEWORK04 PART 2 - JIVITESH POOJARY AND QIWEN ZHU";

DATA V506.Btemp;
	SET V506.Blsa2;
RUN;

/* Answer 4(a)*/
PROC TTEST DATA=V506.Btemp PLOTS=none ALPHA=0.01 SIDES=2;
	CLASS SEX;
	VAR DBP;
RUN;

/* Answer 4(b)*/
PROC TTEST DATA=V506.Btemp PLOTS=none ALPHA=0.05 SIDES=2;
	WHERE SEX ='F';
		CLASS Smoker;
		VAR weight;
RUN;
